const puppeteer = require("puppeteer");
const path = require("path");
const fs = require("fs");

const generateMonthlyPDF = async ({ user, month, totals }) => {
  const browser = await puppeteer.launch({
    headless: "new",
  });

  const page = await browser.newPage();

  const htmlContent = `
    <html>
    <head>
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 40px;
        }
        h1 {
          text-align: center;
        }
        .section {
          margin-top: 20px;
        }
        .kpi {
          display: flex;
          justify-content: space-between;
        }
        .card {
          border: 1px solid #ccc;
          padding: 15px;
          width: 22%;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <h1>Personal Budget Management Tool (NidhiFlow)</h1>
      <p style="text-align:center;"><em>"Track Smart. Save Smart. Grow Smart."</em></p>

      <div class="section">
        <p><strong>Month:</strong> ${month}</p>
        <p><strong>Name:</strong> ${user?.name || ""}</p>
        <p><strong>Email:</strong> ${user?.email || ""}</p>
        <p><strong>Generated On:</strong> ${new Date().toLocaleDateString()}</p>
      </div>

      <div class="section">
        <h2>Financial Summary</h2>
        <div class="kpi">
          <div class="card">
            <h3>Total Income</h3>
            <p>₹ ${totals.totalIncome}</p>
          </div>
          <div class="card">
            <h3>Total Expense</h3>
            <p>₹ ${totals.totalExpense}</p>
          </div>
          <div class="card">
            <h3>Savings</h3>
            <p>₹ ${totals.savings}</p>
          </div>
          <div class="card">
            <h3>Savings %</h3>
            <p>${totals.savingsPercent}%</p>
          </div>
        </div>
      </div>

      <div class="section">
        <p style="text-align:center; margin-top:40px;">
          Generated by NidhiFlow
        </p>
      </div>

    </body>
    </html>
  `;

  await page.goto(
  `http://localhost:5000/api/reports/monthly-html/${user._id}/${month}`,
  { waitUntil: "networkidle0" }
);

  const reportsDir = path.join(__dirname, "../reports");
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir);
  }

  const filePath = path.join(
    reportsDir,
    `NidhiFlow-${month}-Report.pdf`
  );

  await page.pdf({
    path: filePath,
    format: "A4",
    printBackground: true,
  });

  await browser.close();

  return filePath;
};

module.exports = generateMonthlyPDF;