import React from "react";
import "./pdfReport.css";

const PDFReportLayout = ({ user, month, kpis, charts }) => {
  return (
    <div id="pdf-report" className="pdf-container">

      {/* HEADER */}
      <div className="pdf-header">
        <h1>Personal Budget Management Tool (NidhiFlow)</h1>
        <p className="tagline">"Track Smart. Save Smart. Grow Smart."</p>

        <div className="meta">
          <div><strong>Month:</strong> {month}</div>
          <div><strong>Name:</strong> {user?.name}</div>
          <div><strong>Email:</strong> {user?.email}</div>
          <div><strong>Generated On:</strong> {new Date().toLocaleDateString()}</div>
        </div>
      </div>

      {/* KPI SECTION */}
      <div className="kpi-section">
        <div className="kpi-card">
          <h3>Total Income</h3>
          <p>₹ {kpis.totalIncome}</p>
        </div>

        <div className="kpi-card">
          <h3>Total Expense</h3>
          <p>₹ {kpis.totalExpense}</p>
        </div>

        <div className="kpi-card">
          <h3>Savings</h3>
          <p>₹ {kpis.savings}</p>
        </div>

        <div className="kpi-card">
          <h3>Savings %</h3>
          <p>{kpis.savingsPercent}%</p>
        </div>
      </div>

      {/* CHART GRID */}
      <div className="chart-grid">
        {charts.map((chart, index) => (
          <div key={index} className="chart-box">
            {chart}
          </div>
        ))}
      </div>

      <div className="watermark">
        Generated by NidhiFlow
      </div>

    </div>
  );
};

export default PDFReportLayout;